# fly.toml file generated for api-crud-challenge on 2023-02-17T21:29:08-05:00

app = "api-crud-challenge"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  DATABASE_ENVIRONMENT = "production"
  NODE_ENV = "production"
  PORT = "8080"

[experimental]
  auto_rollback = true
  cmd = ["npm run start"]

[deploy]
  release_command = "npm run migrate-prod"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
